
branch:
  default: master

docker:
  # xxx registry: registry.archive.org
  args: ""

scripts:
  container:
    start:
      # example:
      - /usr/local/sbin/nginx -s reload
  branch:
    start:
      # xxx set this up in deploy.sh # xxx do even faster less2css + nav
      - echo xxx
      - vr i
      - echo xxx
triggers:
  # xxx less2css triggers

reverse_proxy: localhost:6666
