
branch:
  default: master

docker:
  # registry: registry.archive.org
  args: ""

scripts:
  container:
    start:
      # try to ensure nginx is up first
      - sleep 15
      - /usr/local/sbin/nginx -s reload
  branch:
    start:
      # this is faster than `vr i` -- by not making .min.js (slow part):
      - mkdir -p www/sf/includes/build.new
      - vr lessc
      - vr hash
      - vr nav
      - vr hotswap
      - vr copy-files

triggers: # xxx
  - www/sf/includes/less/**/
  - vr lessc

reverse_proxy: localhost:6666
